######################################################################
# Automatically generated by qmake (3.0) Thu Oct 19 10:56:12 2017
######################################################################

TEMPLATE = app
TARGET = ESD
INCLUDEPATH += .
QT += widgets sql
LIBS += -lmysqld 

# Input
SOURCES += main.cpp
