#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QString>

extern QString NEW; 
extern QString OLD;
extern QString DIRECTED;
extern QString UNDIRECTED;
extern QString DEFAULT;
extern QString UNDIRECTEDTAIL;
extern QString DIRECTEDTAIL;
extern QString DIRECTEDHEAD;
extern QString DIRECTED;
extern QString PAST;
extern QString FUTURE;
extern QString MANUAL;
extern QString ASSISTED;
extern QString COLLIGATEPATHSACTION;
extern QString COLLIGATEPATHSATTACTION;
extern QString COLLIGATESEMIPATHSACTION;
extern QString COLLIGATESEMIPATHSATTACTION;
extern QString COLLIGATEFREEACTION;
extern QString COLLIGATEFREEATTACTION;
extern QString MAKEMACROACTION;
extern QString PATHS;
extern QString PATHSATT;
extern QString NOCONSTRAINT;
extern QString NOCONSTRAINTATT;
extern QString SEMIPATHS;
extern QString SEMIPATHSATT;
extern QString DISAGGREGATEACTION;
extern QString RECOLOREVENTSACTION;
extern QString RECOLORLABELSACTION;
extern QString COLORLINEAGEACTION;
extern QString REMOVELINKAGEACTION;
extern QString KEEPLINKAGEACTION;
extern QString ACCEPTLINKAGEACTION;
extern QString REJECTLINKAGEACTION;
extern QString SETTLEACTION;
extern QString PARALLELACTION;
extern QString NORMALIZEACTION;
extern QString CLOSEGAPACTION;
extern QString CHANGEDESCRIPTIONACTION;
extern QString IGNOREMEACTION;
extern QString REMOVENORMALLINKAGEACTION;
extern QString CHANGECOMMENTACTION;
extern QString ENTITY;
extern QString INCIDENT;
extern QString MACRO;
extern QString CREATED;
extern QString EVENTGRAPH;
extern QString NETWORKGRAPH;
extern QString OCCURRENCEGRAPH;
extern QString HIDENODE;
extern QString SETPERSISTENT;
extern QString UNSETPERSISTENT;
extern QString ADDLINE;
extern QString ADDSINGLEARROW;
extern QString ADDDOUBLEARROW;
extern QString ADDTEXT;
extern QString ADDELLIPSE;
extern QString ADDRECT;
extern QString CHANGELINECOLOR;
extern QString TOGGLEARROW1;
extern QString TOGGLEARROW2;
extern QString DELETELINE;
extern QString CHANGETEXT;
extern QString CHANGETEXTCOLOR;
extern QString DELETETEXT;
extern QString CHANGEELLIPSECOLOR;
extern QString DELETEELLIPSE;
extern QString CHANGERECTCOLOR;
extern QString DELETERECT;
extern QString ADDLINKAGEACTION;
extern QString SELECTFOLLOWERSACTION;
extern QString SELECTPREDECESSORSACTION;
extern QString ENTITIES;
extern QString AUTOASSIGNALLACTION;
extern QString AUTOASSIGNSPECIFICACTION;
extern QString UNASSIGNALLACTION;
extern QString MERGEATTRIBUTESACTION;
extern QString COPYDESCRIPTIONTOTEXTACTION;
extern QString COPYOBJECT;
extern qreal Pi;

#endif

